[package]
name = "cell"
version = "0.1.0"
authors = ["Shaharyar Ahmed <shaharyar.ahmed1121@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1"
unicode-segmentation = "1"
