name: cell-bin
base: core18 
version: '0.1'
summary: A Minimal command line text editor 
description: |
  Cell is a minimal command line text editor developed using Rust. 
  It is still in development. It is an open source project so feel free to contribuite!

  https://github.com/ShaharyarAhmed-bot/cell

grade: stable
confinement: strict

parts:
  cell-bin:
    source: https://github.com/ShaharyarAhmed-bot/cell.git
    plugin: rust

apps:
  cell-bin:
    command: bin/cell
