name: cellionor 
base: core18 
version: '0.1'
summary: A Minimal command line text editor # 79 char long summary
description: |
  Cellionor or cell for short is a minimal command line text editor developed using Rust. 
  It is still in development. It is an open source project so feel free to contribuite!

  https://github.com/ShaharyarAhmed-bot/cell

grade: stable
confinement: classic

parts:
  cellionor:
    source: https://github.com/ShaharyarAhmed-bot/cell.git
    plugin: rust

apps:
  cellionor:
    command: bin/cell
